### ISSUE TITLE
通讯超时

### ISSUE THREAD

**Issue by jhqwqmc** [MineYuanlu/yuanluServerDo#2]
请问提示服务器通讯超时，请联系管理员是出现了什么问题
我在生成的配置文件中没有找到可以配置ip及端口的设置

**Comment by MineYuanlu** [comment]
请提供一下代理服务器版本和子服务器版本，再说明一下是在执行什么命令时遇到的。

通讯超时是指代理服务器与服务器群组之间的通讯，是建立在玩家与服务器链接之上的，无需设置ip及端口。
