### ISSUE TITLE
velocity无法自动补全

### ISSUE THREAD

**Issue by tiandan6666** [MineYuanlu/yuanluServerDo#7]
进入下游提示“服务器版本不一致：1.2.1-SNATHOST <-> Unknown”
下游使用[yuanluServerDo-bukkit-velocity-1.2.1-SNATHOST.jar]，velocity使用[yuanluServerDo-velocity-1.2.1-SNATHOST.jar]，也尝试过[yuanluServerDo-bukkit-velocity-1.2.1-SNATHOST.jar]。
tpa的补全只有%%%yuanlu-tab-player-list0
推测velocity没有正确加载插件

**Comment by MineYuanlu** [comment]
修复了

**Comment by MineYuanlu** [comment]
https://github.com/MineYuanlu/yuanluServerDo/releases/1.2.2
